from string import uppercase, lowercase, digits
from random import SystemRandom

class Project(object):
    """
    DataCats project settings object
    """

    def generate_passwords(self):
        """
        Generate new DB passwords and store them in self.passwords
        """
        self.passwords = {
            'POSTGRES_PASSWORD': generate_db_password(),
            'CKAN_PASSWORD': generate_db_password(),
            'DATASTORE_RO_PASSWORD': generate_db_password(),
            'DATASTORE_RW_PASSWORD': generate_db_password(),
            }

    def ckan_config_tool_command(self):
        """
        Return a config-tool command with all arguments to update a
        ckan ini file for this project.
        """
        p = self.passwords
        return [
            '/usr/lib/ckan/bin/paster', '--plugin=ckan', 'config-tool',
            '/etc/ckan/default/ckan.ini', '-e',
            'sqlalchemy.url = postgresql://ckan:'
                '{CKAN_PASSWORD}@db:5432/ckan'.format(**p),
            'ckan.datastore.read_url = postgresql://ckan_datastore_readonly:'
                '{DATASTORE_RO_PASSWORD}@db:5432/ckan_datastore'.format(**p),
            'ckan.datastore.write_url = postgresql://ckan_datastore_readwrite:'
                '{DATASTORE_RW_PASSWORD}@db:5432/ckan_datastore'.format(**p),
            'solr_url = http://solr:8080/solr',
            'ckan.storage_path = /var/www/storage',
            ]


def generate_db_password():
    """
    Return a 16-character alphanumeric random string generated by the
    operating system's secure pseudo random number generator
    """
    chars = uppercase + lowercase + digits
    return ''.join(SystemRandom().choice(chars) for x in xrange(16))

